### ISSUE TITLE
Fenced code blocks don't work properly

### ISSUE THREAD

**Issue by ghost** [petethepig/github-markup-preview#1]
A fenced code block like:

``````
```ruby
puts "Hello, world!"
```
``````

Should look like:

``` ruby
puts "Hello, world!"
```

but instead it looks like:

`ruby puts "Hello, world!"`

I guess you're not using GitHub flavored Markdown?

**Comment by petethepig** [comment]
Seems like syntax highlighting doesn't work. I will work on that.
Thank you for the feedback.
